### ISSUE TITLE
backports/__init__.py should probably be a  PEP 420 implicit namespace in Python 3.3+

### ISSUE THREAD

**Issue by nchepanov** [jaraco/backports.entry_points_selectable#5]
I was repackaging `configparser` and `backports.entry_points_selectable` into a Debian distribution and it turned out that both packages provide `backports/__init__.py`. When installed with `pip` - it [doesn't complain](https://github.com/pypa/pip/issues/4625) about it, but other packaging systems are more strict:

```
.../lib/python3.10/site-packages/backports/__pycache__/__init__.cpython-310.pyc
duplicated when installing python3.10-configparser and python3.10-backports-entry-points-selectable.
```

I could patch either package, but it's not clear which one should provide `backports/__init__.py` making them individually installable.

I see that `site-packages/backports/__init__.py` uses https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages 

```
__path__ = __import__('pkgutil').extend_path(__path__, __name__)  # type: ignore
```

One way around this could be:

* having a new `backports` installable package that provides `backports/__init__.py` to all packages in the namespace and is a `install_requires`
* having all packages under the namespace declare `install_requires=['backports; python_version < "3.3"']` instead of shipping the `__init__.py` themselves
* naturally, use implicit namespaces in Python 3.3+ - meaning, no `__init__.py` in there

This is the approach I've seen work before on a scale of hundreds of subpackages. But I'm open to other possibilities too. Happy to contribute if there's a particular solution you like.

PS> The main reason I need it is for the latest version of `virtualenv`

**Comment by nchepanov** [comment]
After further experimenting with this, I'd like to propose conditionally not including `backports/__init__.py` in Python 3.3+. This solves all the problems for modern versions of Python and uses the most recommended PEP 420 implicit namespaces. Additionally, you will be able to add more submodules to `backports.`

```
(venv) ➜ pip install configparser backports.entry_points_selectable
Collecting configparser
  Downloading configparser-5.0.2-py3-none-any.whl (19 kB)
Collecting backports.entry_points_selectable
  Downloading backports.entry_points_selectable-1.1.0-py2.py3-none-any.whl (6.2 kB)
Installing collected packages: configparser, backports.entry-points-selectable
Successfully installed backports.entry-points-selectable-1.1.0 configparser-5.0.2
(venv) ➜ rm venv/lib/python3.9/site-packages/backports/__init__.py venv/lib/python3.9/site-packages/ba
ckports/__pycache__/__init__.cpython-39.pyc
(venv) ➜ python3.9
Python 3.9.5 (default, Jun  3 2021, 17:59:00)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports.entry_points_selectable as e
>>> e
<module 'backports.entry_points_selectable'
from '/Users/nchepanov/tmp/pep420/venv/lib/python3.9/site-packages/backports/entry_points_selectable.py'>
>>> import backports.configparser as c
>>> c
<module 'backports.configparser'
from '/Users/nchepanov/tmp/pep420/venv/lib/python3.9/site-packages/backports/configparser/__init__.py'>
```

**Comment by jaraco** [comment]
I'm sorry to hear you've encountered this issue. I've heard this complaint as well with those working to incorporate the jaraco.* series of packages into package managers that expect packages' filenames not to overlap.

These backports projects implement the design of the [backports](https://pypi.org/project/backports/) project. My guess is the design you propose would need to be implemented there. It looks like that project hasn't been updated in over a decade and was hosted on bitbucket, so it may prove a bit difficult to revive.

I'm also not confident that it's possible to safely publish packages in the way you describe. That is, is it possible to publish `backports.configparser` with Python 2 compatibility but without an `__init__.py` in that distribution (only in a dependency)? I see that it's possible in a pure-Python sense, but I'm not confident the packaging tools can handle a package without an `__init__` (outside of PEP 420).

@brandon-rhodes Do you have any opinion on @nchepanov's suggestion above? Are you interested in reviving the backports project, possibly with code implementing the common filename? If not, would you be willing to hand off that package so I can carry the torch for it?

**Comment by brandon-rhodes** [comment]
@jaraco — Debian has for many years packaged wide collections of Python 2 packages that live under the same namespace, like `zope.interface` and `zope.testing`, so this is surely a solved problem. My suggestion is that @nchepanov take a look at that prior work, and that the Debian packages for `backports.*` can simply do whatever it was that the `zope.*` packages have always done to keep Debian happy despite every Zope package providing the same `zope/__init__.py` file. Let me know if that works!

**Comment by nchepanov** [comment]
Thank you @brandon-rhodes, I will surely take a look. From what I found so far, they do something special to accommodate  this in Debian. e.g. https://packages.debian.org/jessie/all/python3-zope.event/filelist has `.../zope/__init__$py.class`.

However I'd like to raise the question of whether it is the right thing to do regardless of Debian:

What is the reason for `namespace/__init__.py` to be included in all `backports.` namespaced packages in modern versions of Python? Is this an intentional decision, or a technical debt that we can work on?

I'm yet to hear any rational besides - we've always done it, and nobody complained before. Is this the approach you would have taken if you were building an entirely new hierarchy of Python 3 only namespaced libraries? Is this approach consistent with [best practices ](https://packaging.python.org/guides/packaging-namespace-packages/)? Is it reasonable to rely on `pip` [bug](https://github.com/pypa/pip/issues/4625) that many users have already complained about? 

I was able to work around it for now, by patching the source distribution and removing the conflicting file. I wonder if we can do better.

**Comment by brandon-rhodes** [comment]
> I'm yet to hear any rational besides - we've always done it, and nobody complained before. Is this the approach you would have taken if you were building an entirely new hierarchy of Python 3 only namespaced libraries?

I am going to assume that you are not intending your tone to be condescending — but, the reason that you didn't hear a rationale is only because you didn't ask for one. Now that you have actually asked: we're happy to explain that the `backports.*` modules were invented to make new Python 3 modules available in Python 2, so they are deliberately and consistently compatible with Python 2 and its import mechanism, including requiring `__init__.py` at the package level. The whole point is for old Python 2 projects that are still being maintained to always be able to download and install the most recent version of a `backports.*` module or package.

(There may by this point be 3rd party modules that instead of targeting Python 2 are merely trying to offer Python 3 package to earlier versions of Python 3? Since, of course, people can publish anything they want under the namespace without asking for permission. But the original purpose was the support of Python 2.)

**Comment by brandon-rhodes** [comment]
(I would update the "backports" description on PyPI to make clear that Python 2 was among the targeted earlier versions, but I'm not sure that the modern rewritten PyPI supports updating project descriptions? I just checked and there's not an "edit" button.)

**Comment by jaraco** [comment]
> (There may by this point be 3rd party modules that instead of targeting Python 2 are merely trying to offer Python 3 package to earlier versions of Python 3? Since, of course, people can publish anything they want under the namespace without asking for permission. But the original purpose was the support of Python 2.)

I do think as we get get closer to a future without Python 2, the `backports` namespace will still have value, so I'd like to express interest in continuing to maintain it for backports that don't necessarily support Python 2.

`configparser` is in fact one such project whose earlier releases provided backward compatibility to Python 2 but subsequent releases only support Python 3.6+:

```
backports.entry_points_selectable main $ py -2 -m pip-run configparser -- -c pass
Collecting configparser
  Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Installing collected packages: configparser
Successfully installed configparser-4.0.2
backports.entry_points_selectable main $ py -3 -m pip-run configparser -- -c pass
Collecting configparser
  Downloading configparser-5.1.0-py3-none-any.whl (19 kB)
Installing collected packages: configparser
Successfully installed configparser-5.1.0
```

Note that although the project is called `configparser`, it does present the `backports.configparser` package.

> (I would update the "backports" description on PyPI to make clear that Python 2 was among the targeted earlier versions, but I'm not sure that the modern rewritten PyPI supports updating project descriptions? I just checked and there's not an "edit" button.)

That's right. The project description is derived from the Description metadata field of the most recent uploaded package (or of the local package when `twine register` is run).

If you'd like help, I'd be willing to (co-)maintain the `backports` project. All I'd need is maintainer (or owner) access to the PyPI repo (username is same). If you still have the original mercurial repo where the content was authored, I'd prefer to use that. Since bitbucket is retired, it's probably not available online, but you may have a clone of it on a local machine. If you'd like help migrating that to Github, I can help with that. Feel free to run an `hg archive` in the folder or simply ball it up and [upload it here](https://www.dropbox.com/request/w5znIfbEbSZP5oM2tS6r), and I can take care of migrating it to Github. I'll let you maintain as much or little custody of the project as you'd like (including dropping my access after the migration if that's what you'd prefer). LMK.

**Comment by brandon-rhodes** [comment]
@jaraco — I would be happy to elevate someone else to maintainer of `backports`, and I'll go look for the source code. But, to clarify the situation: the actual `backports` module never gets installed on anyone’s machine, correct? It’s just a placeholder that stops anyone from claiming the name on PyPI, if I remember correctly? (But I could be wrong, it’s been a long time!) So your goal would simply be to update its description on PyPI so that it could offer advice to all of its daughter projects about — switching to PEP 420 namespace packaging if they detect Python ≥ 3.3 or something like that?

I am interested in hearing your detailed proposal, and to learn what will happen if, of *n* backports packages that someone tries to install, what if half of them upgrade to the PEP 420 idea but half don’t get the update and still deliver `__init__.py` files?

**Comment by brandon-rhodes** [comment]
(Oh, and: the project did get migrated to GitHub, it looks like! https://github.com/brandon-rhodes/backports )

**Comment by jaraco** [comment]
> But, to clarify the situation: the actual `backports` module never gets installed on anyone’s machine, correct?

Yes, that's correct, and you can verify by looking at the [only release](https://pypi.org/project/backports/1.0/) and noticing there are no downloads. It's possible one will need to create an additional release (again with no downloads) for the project.

Glad to see there's a github repo. I'll make some suggestions there.

**Comment by jaraco** [comment]
Now that the guidance with backports is being updated in that project, there's nothing more this project can do. It's following the best recommendation for projects requiring Python < 3.2.
